name: Pact contracts

on:

  push:

  workflow_dispatch:

jobs:

  test-pact:
    name: Test KDA smart contracts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install Pact
        run: |
          PACT_VERSION="5.4ce"
          PACT_HASH="b769"
          curl -LO https://github.com/kda-community/pact-5/releases/download/$PACT_VERSION/pact-$PACT_VERSION-$PACT_HASH-ubuntu-22.04.tar.gz
          mkdir -p .bin
          tar -xvzf pact-$PACT_VERSION-$PACT_HASH-ubuntu-22.04.tar.gz -C .bin pact
          chmod +x .bin/pact
      - name: Add Pact to PATH
        run: echo "PATH=$PATH:$GITHUB_WORKSPACE/.bin" >> $GITHUB_ENV

      - name: Unlock governance for tests
        run: |
          cat otc_deal_locker.pact | sed "s/(defconst FROZEN-MODULE true)/(defconst FROZEN-MODULE false)/g" > .tmp
          mv .tmp otc_deal_locker.pact

      - name: Run tests
        run: |
          pact otc_deal_locker.repl
          pact otc_deal_locker_helper.repl
          pact gas-station.repl